### ISSUE TITLE
解决 https 加一个 ` --ssl-insecure` 参数即可 

### ISSUE THREAD

**Issue by signfind** [carr0t2/nps-auth-bypass#1]
`mitmdump --ssl-insecure -s main.py -p 8000 --mode reverse:https://xxx.xxx.xxx:8080/`
![image](https://user-images.githubusercontent.com/97871760/183041985-ed6246fa-e26a-4157-b315-7bce00c61ef5.png)

**Comment by carr0t2** [comment]
谢谢 已完善文档
